name: 'Chef InSpec Compliance Scan'
on:
  workflow_dispatch:
  
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout InSpec Profile from Repository
        uses: actions/checkout@v4
      
      - name: Run InSpec Scan with Docker
        env:
          CHEF_LICENSE: accept-silent
        run: |
          docker run --rm \
            -v $(pwd):/share \
            -e CHEF_LICENSE=accept-silent \
            chef/inspec:latest exec /share/ssh-baseline \
            --target local:// \
            --reporter cli json:/share/inspec-report.json
        continue-on-error: true
          
      - name: Upload InSpec Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inspec-scan-report
          path: inspec-report.json
      
      - name: Display Scan Summary
        if: always()
        run: |
          if [ -f inspec-report.json ]; then
            echo "### InSpec Scan Results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Scan completed. Download the full report from artifacts." >> $GITHUB_STEP_SUMMARY
          fi
