name: 'Chef InSpec Compliance Scan'

on:
  workflow_dispatch:

jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run InSpec Scan
        uses: chef/action-inspec@v1
        with:
          profile: './ssh-baseline'
          target: 'local://'
          reporter: 'cli json'

      - name: Upload InSpec Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inspec-scan-report
          path: inspec-report.json
