name: 'Chef InSpec Compliance Scan'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code (your InSpec profile)
      - name: Checkout InSpec Profile from Repository
        uses: actions/checkout@v4

      # Step 2: Run the InSpec scan on the local runner
      - name: Run InSpec Scan
        uses: chef/action-inspec@v1
        with:
          profile: './ssh-baseline'
          target: 'local://'
          # Use the full JSON reporter for rich data, and CLI for easy viewing in logs
          reporter: 'cli json' 
          
      # Step 3: Store the scan report as a downloadable artifact
      # This is for archival and manual inspection. It runs even if the InSpec scan fails.
      - name: Upload InSpec Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inspec-scan-report
          # The default output file from the action is inspec-report.json
          path: inspec-report.json

# --- REMOVED SECTION ---
# The entire "Upload Results to DefectDojo" step has been removed.
# You also no longer need the DEFECTDOJO_URL and DEFECTDOJO_API_KEY secrets.
